const studentDetails = [
  {
    id: "STU2023002",
    firstName: "Aarav",
    lastName: "Sharma",
    profilePicture: "https://randomuser.me/api/portraits/men/1.jpg",
    registrationNumber: "STU2023002",
    class: "9th Grade",
    age: 15,
    mobileNumber: "9876543210",
    email: "aarav.sharma@gmail.com",
    parentDetails: {
      firstName: "",
      lastName: "",
      phoneNumber: "",
      emailAddress: "",
      profilePicture: "",
    },
  },
  {
    id: "STU2023003",
    firstName: "Ananya",
    lastName: "Verma",
    profilePicture: "https://randomuser.me/api/portraits/women/2.jpg",
    registrationNumber: "STU2023003",
    class: "8th Grade",
    age: 14,
    mobileNumber: "9123456789",
    email: "ananya.verma@gmail.com",
    parentDetails: {
      firstName: "",
      lastName: "",
      phoneNumber: "",
      emailAddress: "",
      profilePicture: "",
    },
  },
  {
    id: "STU2023004",
    firstName: "Ishaan",
    lastName: "Gupta",
    profilePicture: "https://randomuser.me/api/portraits/men/3.jpg",
    registrationNumber: "",
    class: "10th Grade",
    age: '',
    mobileNumber: "9012345678",
    email: "ishaan.gupta@gmail.com",
    parentDetails: {
      firstName: "",
      lastName: "",
      phoneNumber: "",
      emailAddress: "",
      profilePicture: "",
    },
  },
  {
    id: "STU2023005",
    firstName: "Meera",
    lastName: "Raj",
    profilePicture: "https://randomuser.me/api/portraits/women/4.jpg",
    registrationNumber: "",
    class: "11th Grade",
    age: 17,
    mobileNumber: "9988776655",
    email: "meera.raj@gmail.com",
    parentDetails: {
      firstName: "",
      lastName: "",
      phoneNumber: "",
      emailAddress: "",
      profilePicture: "",
    },
  },
  {
    id: "STU2023006",
    firstName: "Rohan",
    lastName: "Das",
    profilePicture: "https://randomuser.me/api/portraits/men/5.jpg",
    registrationNumber: "STU2023006",
    class: "12th Grade",
    age: '',
    mobileNumber: "8877665544",
    email: "rohan.das@gmail.com",
    parentDetails: {
      firstName: "",
      lastName: "",
      phoneNumber: "",
      emailAddress: "",
      profilePicture: "",
    },
  },
  {
    id: "STU2023007",
    firstName: "Simran",
    lastName: "Kaur",
    profilePicture: "https://randomuser.me/api/portraits/women/6.jpg",
    registrationNumber: "STU2023007",
    class: "7th Grade",
    age: 13,
    mobileNumber: "8765432109",
    email: "simran.kaur@gmail.com",
    parentDetails: {
      firstName: "",
      lastName: "",
      phoneNumber: "",
      emailAddress: "",
      profilePicture: "",
    },
  },
  {
    id: "STU2023008",
    firstName: "Arjun",
    lastName: "Nair",
    profilePicture: "https://randomuser.me/api/portraits/men/7.jpg",
    registrationNumber: "STU2023008",
    class: "6th Grade",
    age: 12,
    mobileNumber: "7654321098",
    email: "arjun.nair@gmail.com",
    parentDetails: {
      firstName: "",
      lastName: "",
      phoneNumber: "",
      emailAddress: "",
      profilePicture: "",
    },
  },
  {
    id: "STU2023009",
    firstName: "Kavya",
    lastName: "Jain",
    profilePicture: "https://randomuser.me/api/portraits/women/8.jpg",
    registrationNumber: "STU2023009",
    class: "5th Grade",
    age: '',
    mobileNumber: "6543210987",
    email: "kavya.jain@gmail.com",
    parentDetails: {
      firstName: "",
      lastName: "",
      phoneNumber: "",
      emailAddress: "",
      profilePicture: "",
    },
  },
  {
    id: "STU2023010",
    firstName: "Dev",
    lastName: "Patel",
    profilePicture: "https://randomuser.me/api/portraits/men/9.jpg",
    registrationNumber: "STU2023010",
    class: "4th Grade",
    age: 10,
    mobileNumber: "5432109876",
    email: "dev.patel@gmail.com",
    parentDetails: {
      firstName: "",
      lastName: "",
      phoneNumber: "",
      emailAddress: "",
      profilePicture: "",
    },
  },
  {
    id: "STU2023011",
    firstName: "Pooja",
    lastName: "Singh",
    profilePicture: "https://randomuser.me/api/portraits/women/10.jpg",
    registrationNumber: "STU2023011",
    class: "3rd Grade",
    age: 9,
    mobileNumber: "4321098765",
    email: "pooja.singh@gmail.com",
    parentDetails: {
      firstName: "",
      lastName: "",
      phoneNumber: "",
      emailAddress: "",
      profilePicture: "",
    },
  },
  {
    id: "STU2023012",
    firstName: "Aditya",
    lastName: "Roy",
    profilePicture: "https://randomuser.me/api/portraits/men/11.jpg",
    registrationNumber: "STU2023012",
    class: "2nd Grade",
    age: 8,
    mobileNumber: "9876543211",
    email: "aditya.roy@gmail.com",
    parentDetails: {
      firstName: "",
      lastName: "",
      phoneNumber: "",
      emailAddress: "",
      profilePicture: "",
    },
  },
  {
    id: "STU2023013",
    firstName: "Nisha",
    lastName: "Yadav",
    profilePicture: "https://randomuser.me/api/portraits/women/12.jpg",
    registrationNumber: "STU2023013",
    class: "1st Grade",
    age: 7,
    mobileNumber: "8765432101",
    email: "nisha.yadav@gmail.com",
    parentDetails: {
      firstName: "Papa",
      lastName: "Ji",
      phoneNumber: "7855874591",
      emailAddress: "example@papa.gmail.com",
      profilePicture: "",
    },
  },
  {
    id: "STU2023014",
    firstName: "Tanmay",
    lastName: "Joshi",
    profilePicture: "https://randomuser.me/api/portraits/men/13.jpg",
    registrationNumber: "STU2023014",
    class: "10th Grade",
    age: 16,
    mobileNumber: "7654321091",
    email: "tanmay.joshi@gmail.com",
    parentDetails: {
      firstName: "",
      lastName: "",
      phoneNumber: "",
      emailAddress: "",
      profilePicture: "",
    },
  },
  {
    id: "STU2023015",
    firstName: "Priya",
    lastName: "Kapoor",
    profilePicture: "https://randomuser.me/api/portraits/women/14.jpg",
    registrationNumber: "STU2023015",
    class: "9th Grade",
    age: 15,
    mobileNumber: "6543210981",
    email: "priya.kapoor@gmail.com",
    parentDetails: {
      firstName: "",
      lastName: "",
      phoneNumber: "",
      emailAddress: "",
      profilePicture: "",
    },
  },
  {
    id: "STU2023016",
    firstName: "Karan",
    lastName: "Singh",
    profilePicture: "https://randomuser.me/api/portraits/men/15.jpg",
    registrationNumber: "STU2023016",
    class: "8th Grade",
    age: 14,
    mobileNumber: "5432109871",
    email: "karan.singh@gmail.com",
    parentDetails: {
      firstName: "",
      lastName: "",
      phoneNumber: "",
      emailAddress: "",
      profilePicture: "",
    },
  },
  {
    id: "STU2023017",
    firstName: "Sneha",
    lastName: "Pillai",
    profilePicture: "https://randomuser.me/api/portraits/women/16.jpg",
    registrationNumber: "STU2023017",
    class: "7th Grade",
    age: 13,
    mobileNumber: "4321098761",
    email: "sneha.pillai@gmail.com",
    parentDetails: {
      firstName: "",
      lastName: "",
      phoneNumber: "",
      emailAddress: "",
      profilePicture: "",
    },
  },
  {
    id: "STU2023018",
    firstName: "Ritik Malhotra",
    lastName: "Malhotra",
    profilePicture: "https://randomuser.me/api/portraits/men/17.jpg",
    registrationNumber: "STU2023018",
    class: "6th Grade",
    age: 12,
    mobileNumber: "3210987651",
    email: "ritik.malhotra@gmail.com",
    parentDetails: {
      firstName: "",
      lastName: "",
      phoneNumber: "",
      emailAddress: "",
      profilePicture: "",
    },
  },
  {
    id: "STU2023019",
    firstName: "Shreya",
    lastName: "Rao",
    profilePicture: "https://randomuser.me/api/portraits/women/18.jpg",
    registrationNumber: "STU2023019",
    class: "5th Grade",
    age: 11,
    mobileNumber: "2109876541",
    email: "shreya.rao@gmail.com",
    parentDetails: {
      firstName: "",
      lastName: "",
      phoneNumber: "",
      emailAddress: "",
      profilePicture: "",
    },
  },
  {
    id: "STU2023020",
    firstName: "Vishal",
    lastName: "Kumar",
    profilePicture: "https://randomuser.me/api/portraits/men/19.jpg",
    registrationNumber: "STU2023020",
    class: "4th Grade",
    age: 10,
    mobileNumber: "1098765431",
    email: "vishal.kumar@gmail.com",
    parentDetails: {
      firstName: "",
      lastName: "",
      phoneNumber: "",
      emailAddress: "",
      profilePicture: "",
    },
  },
];




export default studentDetails;
